name: noteflow_app
description: "NoteFlow - 智能笔记应用，支持AI功能的现代化笔记管理工具"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  lottie: ^2.4.0
  
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  sqflite: ^2.4.1
  
  # Rich Text Editor
  flutter_quill: ^9.5.23
  
  # Security
  encrypt: ^5.0.1
  local_auth: ^2.3.0
  
  # AI & ML Features
  google_mlkit_text_recognition: ^0.13.0
  speech_to_text: ^6.6.0
  record: ^6.1.0
  audioplayers: ^5.2.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  path: ^1.8.3
  image_picker: ^1.0.5
  share_plus: ^7.0.0
  url_launcher: ^6.2.2
  file_picker: ^6.1.1
  webview_flutter: ^4.8.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.5.7
  
  # Calendar
  table_calendar: ^3.1.2
  
  # UI Enhancement
  flutter_screenutil: ^5.8.4
  loading_animation_widget: ^1.2.0+2
  flutter_smart_dialog: ^4.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.4
  json_serializable: ^6.6.1
  bloc_test: ^9.1.5

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/html/

flutter_intl:
  enabled: true
